### ISSUE TITLE
mix.fonts is not a function

### ISSUE THREAD

**Issue by burknator** [GrandadEvans/laravel-elixir-copy-fonts#1]
Installed as described, but when I run gulp, I get the following error:

```
gulpfile.js:18
    mix.fonts()
        ^

TypeError: mix.fonts is not a function
    at mix (/Users/patrick/Code/promoportal/gulpfile.js:18:9)
    at global.Elixir (/Users/patrick/Code/promoportal/node_modules/laravel-elixir/dist/index.js:21:5)
    at Object.<anonymous> (/Users/patrick/Code/promoportal/gulpfile.js:17:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

Elixir version is "^6.0.0-9".

Gulpfile looks like this:

``` js
elixir(mix => {
    mix.fonts()
       .less('app.less')
       .webpack('app.js');
});
```

**Comment by GrandadEvans** [comment]
Hi, @burknator 
Sorry for the delay in replying: I'm having some quite significant medical issues at the moment which mean I can't do much work/coding at the moment. That being said, I'll try and look at this tomorrow and see if I can re-create it.

**Comment by burknator** [comment]
Hey @GrandadEvans!
Also sorry for the late reply! By all means, get well and skip the coding!
